server.port: 9000
spring:
  application:
    name: board-article-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.29.162.192:3306/article
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
